package com.javadera.shainweb.model;
// Generated 2016/01/20 13:45:58 by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * RoleMaster generated by hbm2java
 */
@Entity
@Table(name = "role_master", uniqueConstraints = @UniqueConstraint(columnNames = "role_name") )
@NamedQueries({
    @NamedQuery(name="RoleMaster.findAllOrderById", query="SELECT rm FROM RoleMaster rm ORDER BY rm.roleId"),
    @NamedQuery(name="RoleMaster.findByName",       query="SELECT rm FROM RoleMaster rm WHERE rm.roleName = :roleName")
})
public class RoleMaster implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int roleId;
	private String roleName;
	private Set<Employee> employees = new HashSet<Employee>(0);

	public RoleMaster() {
	}

	public RoleMaster(int roleId, String roleName) {
		this.roleId = roleId;
		this.roleName = roleName;
	}

	public RoleMaster(int roleId, String roleName, Set<Employee> employees) {
		this.roleId = roleId;
		this.roleName = roleName;
		this.employees = employees;
	}

	@Id

	@Column(name = "role_id", unique = true, nullable = false)
	public int getRoleId() {
		return this.roleId;
	}

	public void setRoleId(int roleId) {
		this.roleId = roleId;
	}

	@Column(name = "role_name", unique = true, nullable = false, length = 50)
	public String getRoleName() {
		return this.roleName;
	}

	public void setRoleName(String roleName) {
		this.roleName = roleName;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "roleMaster")
	public Set<Employee> getEmployees() {
		return this.employees;
	}

	public void setEmployees(Set<Employee> employees) {
		this.employees = employees;
	}

}
